### PR TITLE
Supports permitted array params

### PR DESCRIPTION
**Pull request by MatthewTFarley**

### CODE REVIEW

**Comment by robdimarco** [comment]
I'm not following this. I assume this is for the situation where you are trying to set an array. Isn't this always blanking it out?

**Comment by MatthewTFarley** [comment]
Yes, this is trying to handle the scenario where an array of values is coming in to be set. Not sure what you mean by blanking it out. This change is successfully whitelisting all appropriate values, including array values.

**Comment by MatthewTFarley** [comment]
I'm not sure if it's a good idea to do this, or if it's more straightforward to just define `#create` or `#update` in the controllers where I need array param support.

**Comment by robdimarco** [comment]
Talked with @MatthewTFarley 

Probably better to use the columns to see if it is an [array](http://www.rubydoc.info/docs/rails/4.1.7/ActiveRecord/ConnectionAdapters/PostgreSQLColumn#array-instance_method)

Something like:

```ruby
param_names = associated_model.columns.map do |col|
  next if col.name.in?(parameters_to_ignore_from_update)
  if col.array
    { col.name => [] }
  else
    col.name
  end
end
```

**Comment by robdimarco** [comment]
+1 from me.

**Pull request merged**
